name: "Metadata Update"
description: "Updating metadata"
labels: ["Metadata"]
body:
- type: input
  attributes:
    label: "Metadata file"
    description: "Please provide file name to be updated"
    placeholder: ".txt"
- type: dropdown
  attributes:
    label: "Action type"
    description: "Please provide action for metadata update"
    options:
      - Add
      - Remove
      - Replace
- type: input
  attributes:
    label: "Reference"
    description: "Please provide any reference to justify this metadata update"
    placeholder: "INC0000000/Any other"

- type: textarea
  attributes:
      label: "Content"
      description: "Please provide changes you want to make"
      render: txt
