name: "Metadata Update"
description: "Updating metadata"
labels: "Metadata"
body: 
- type: input
  attributes:
    label: "Action type"
    description: "Please provide action for metadata update"
    placeholder: "Add/Remove/Replace"
