name: "Metadata Update"
description: "Updating metadata"
labels: "Metadata"
body: 
- type: dropdown
  attributes:
    label: "Action type"
    description: "Please provide action for metadata update"
    options:
      - Add
      - Remove
      - Replace
